DROP DATABASE IF EXISTS meetic;
CREATE DATABASE 'meetic';
USE `meetic`;
DROP TABLE IF EXISTS 'user';
DROP TABLE IF EXISTS 'genre';
DROP TABLE IF EXISTS 'loisir';
DROP TABLE IF EXISTS 'user_loisir';
CREATE TABLE 'genre (
    genre_id INT NOT NULL AUTO_INCREMENT,
    genre_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (genre_id)
);
CREATE TABLE user_loisirs (
    user_id INT,
    loisir VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    pseudo VARCHAR(255) NULL,
    birthdate Datetime NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    id_genre INT NOT NULL,
    loisir_name varchar(255) NOT NULL,
    profile_pic VARCHAR(255) DEFAULT NULL,
    status BOOLEAN DEFAULT 1,
    PRIMARY KEY (id),
    FOREIGN KEY (id_genre) REFERENCES genre(genre_id)
);
CREATE TABLE user_loisir(
    id_user INT NOT NULL,
    id_loisir INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES user(id),
    FOREIGN KEY (id_loisir) REFERENCES loisir(id)
);
INSERT INTO genre (genre_name)
VALUES ('Homme'),
    ('Femme'),
    ('Autres');
INSERT INTO loisir (name)
VALUES ('Cuisine'),
    ('Lecture'),
    ('Manga'),
    ('Foot'),
    ('Ballade'),
    ('Randonnee'),
    ('Yoga'),
    ('Danse'),
    ('Peinture'),
    ('Dessin'),
    ('Musique'),
    ('Jardinage'),
    ('Péche'),
    ('Bénévolat');
INSERT INTO user (
        firstname,
        lastname,
        pseudo,
        birthdate,
        email,
        password,
        city,
        country,
        id_genre,
        loisir_name,
        profile_pic
    )
VALUES (
        'Randy',
        'Black',
        'Randys',
        '2005-10-28T00:34:58',
        'randy.black@ore.com',
        MD5('password'),
        'Paris',
        'France',
        2,
        'yoga',
        'Randy_Black.jpg'
    ),
    (
        'Jeffrey',
        'Wheeler',
        'Jef',
        '2000-03-08T00:34:58',
        'jeffrey.wheeler@ota.com',
        MD5('passSecure'),
        'Bordeaux',
        'France',
        1,
        'randonné',
        'Jeffrey_Wheeler.jpg'
    ),
    (
        'Bill',
        'Garza',
        'Bilza',
        '1995-12-10T22:04:23',
        'bill.garza@mom.eu',
        MD5('loveMeetic'),
        'Nantes',
        'France',
        1,
        'Musique',
        'Bill_Garza.jpg'
    ),
    (
        'Duane',
        'Christeen',
        'Christeen',
        '1997-10-06T00:34:58',
        'duane.christensen@ti.fr',
        MD5('passLove'),
        'Toulouse',
        'France',
        2,
        'Dance',
        'Duane_Christeen.jpg'
    ),
    (
        'Brent',
        'Roberta',
        'Brento',
        '2001-05-28T00:34:58',
        'brent.roberta@zivilzit.fr',
        MD5('password123'),
        'Paris',
        'France',
        2,
        'Peinture',
        'Brent_Roberta.jpg'
    ),
    (
        'Franklin',
        'Bailey',
        NULL,
        '2004-02-13T00:34:58',
        'franklin.bailey@ge.com',
        MD5('123pass'),
        'Marseille',
        'France',
        1,
        'Yoga',
        'Franklin_Bailey.jpg'
    ),
    (
        'Alice',
        'Smith',
        'alicelove',
        '1994-08-21',
        'alice.smith@meetic.com',
        MD5('alice123'),
        'Lyon',
        'France',
        2,
        'Lecture',
        'alice_smith.jpg'
    ),
    (
        'John',
        'Doe',
        'johndoe123',
        '1992-05-15',
        'john.doe@mtoa.com',
        MD5('johnPassword123'),
        'Paris',
        'France',
        1,
        'Football',
        'john_doe.jpg'
    ),
    (
        'Emma',
        'Wilson',
        'emma_wilson',
        '1997-11-25',
        'emma.wilson@epita.com',
        MD5('emma123'),
        'Bordeaux',
        'France',
        2,
        'Voyages',
        'emma_wilson.jpg'
    ),
    (
        'Max',
        'Dupont',
        'maximus',
        '1990-03-12',
        'max.dupont@egoogle.com',
        MD5('maxpassword'),
        'Toulouse',
        'France',
        1,
        'Musique',
        'Max_Dupont.jpg'
    ),
    (
        'Sarah',
        'Lee',
        'sarah_love',
        '1996-07-10',
        'sarah.lee@sql.com',
        MD5('sarah12345'),
        'Nice',
        'France',
        2,
        'Danse',
        'Sarah_Lee.jpg'
    ),
    (
        'Paul',
        'Martin',
        'paul_king',
        '1988-10-02',
        'paul.martin@mart.com',
        MD5('paul1234'),
        'Marseille',
        'France',
        1,
        'Cinéma',
        'Paul_Martin.jpg'
    ),
    (
        'Alice',
        'Smith',
        'alicelove',
        '1994-08-21',
        'alice.smith@beryoe.com',
        MD5('alice123'),
        'Lyon',
        'France',
        2,
        'Lecture',
        'Alice_Smith.jpg'
    ),
    (
        'John',
        'Doe',
        'johndoe123',
        '1992-05-15',
        'john.doe@eindex.com',
        MD5('johnPassword123'),
        'Paris',
        'France',
        1,
        'Football',
        'John_Doe.jpg'
    ),
    (
        'Jean',
        'Dupont',
        'jdupont',
        '1985-03-15',
        'jean.dupont@exemple.com',
        MD5('jean123'),
        'Lille',
        'France',
        1,
        'Cyclisme',
        'Jean_Dupont.jpg'
    ),
    (
        'Clara',
        'Miller',
        'clara_m',
        '1992-09-10',
        'clara.miller@exemple.com',
        MD5('clara123'),
        'Paris',
        'France',
        2,
        'Lecture',
        'Clara_Miller.jpg'
    ),
    (
        'Louis',
        'Lemoine',
        'louislem',
        '1995-02-20',
        'louis.lemoine@exemple.com',
        MD5('louis123'),
        'Lyon',
        'France',
        1,
        'Voyages',
        'Louis_Lemoine.jpg'
    ),
    (
        'Sophie',
        'Benoit',
        'sophie_benoit',
        '1994-06-05',
        'sophie.benoit@exemple.com',
        MD5('sophie123'),
        'Marseille',
        'France',
        2,
        'Yoga',
        'Sophie_Benoit.jpg'
    ),
    (
        'Marc',
        'Petit',
        'marcp',
        '1998-11-30',
        'marc.petit@exemple.com',
        MD5('marc123'),
        'Toulouse',
        'France',
        1,
        'Football',
        'Marc_Petit.jpg'
    ),
    (
        'Isabelle',
        'Faure',
        'isabellefaure',
        '1990-04-18',
        'isabelle.faure@exemple.com',
        MD5('isabelle123'),
        'Nice',
        'France',
        2,
        'Cuisine',
        'Isabelle_Faure.jpg'
    ),
    (
        'Pierre',
        'Lemoine',
        'pierrelm',
        '1993-07-22',
        'pierre.lemoine@exemple.com',
        MD5('pierre123'),
        'Bordeaux',
        'France',
        1,
        'Randonnée',
        'Pierre_Lemoine.jpg'
    ),
    (
        'Lucie',
        'Robert',
        'lucie_r',
        '1996-01-12',
        'lucie.robert@exemple.com',
        MD5('lucie123'),
        'Nantes',
        'France',
        2,
        'Danse',
        'Lucie_Robert.jpg'
    ),
    (
        'Antoine',
        'Dupuis',
        'antoinedup',
        '1990-12-05',
        'antoine.dupuis@exemple.com',
        MD5('antoine123'),
        'Paris',
        'France',
        1,
        'Cinéma',
        'Antoine_Dupuis.jpg'
    ),
    (
        'Juliette',
        'Leclerc',
        'juliette_leclerc',
        '1997-05-18',
        'juliette.leclerc@exemple.com',
        MD5('juliette123'),
        'Toulouse',
        'France',
        2,
        'Peinture',
        'Juliette_Leclerc.jpg'
    );